# PHASE 5 — Blanket Augmentation (Ablation Control, No Evidence-Filtering)

## Cell 1 — Install dependencies

In [1]:
import subprocess, sys
def _pip_install(pkg):
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", pkg], check=False)
for pkg in ["ultralytics", "opencv-python-headless", "openpyxl"]:
    _pip_install(pkg)
import torch
print("Torch:", torch.__version__, "| CUDA available:", torch.cuda.is_available())
DEVICE = 0 if torch.cuda.is_available() else "cpu"
print("Using device:", DEVICE)

Torch: 2.10.0+cu128 | CUDA available: True
Using device: 0

## Cell 2 — Imports

In [2]:
import os, glob, json, random, shutil, time
import numpy as np
import pandas as pd
import cv2
import yaml as pyyaml
from ultralytics import YOLO

print("Imports OK")

Imports OK

## Cell 3 — Configuration

Blanket = ALL three Phase 3 degradation types applied with EQUAL, unfiltered
probability -- no XAI evidence gate. Everything else (architecture, epochs,
optimizer, baseline augmentation) is identical to Phase 5 Variant 1 for a fair
comparison.

In [3]:
SEED = 42
IMG_SIZE = 640
EVAL_CONF = 0.001
IOU_THRESHOLD = 0.70

TRAIN_EPOCHS = 150
TRAIN_PATIENCE = 30
TRAIN_BATCH = 12
TRAIN_OPTIMIZER = "SGD"
TRAIN_LR0 = 0.01
TRAIN_LRF = 0.01
TRAIN_MOMENTUM = 0.937
TRAIN_WEIGHT_DECAY = 0.0005
TRAIN_WARMUP_EPOCHS = 3.0
TRAIN_WARMUP_MOMENTUM = 0.8
TRAIN_WARMUP_BIAS_LR = 0.1
TRAIN_SEED = 42
TRAIN_DETERMINISTIC = True
TRAIN_CLOSE_MOSAIC = 20
TRAIN_COS_LR = False

BASELINE_AUG = dict(
    hsv_h=0.02, hsv_s=0.7, hsv_v=0.5,
    degrees=10.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0,
    flipud=0.0, fliplr=0.5, bgr=0.0,
    mosaic=1.0, mixup=0.0, cutmix=0.0, copy_paste=0.0, copy_paste_mode="flip",
    auto_augment="randaugment", erasing=0.4,
)

# ---------------------------------------------------------------------------
# BLANKET augmentation -- all three Phase 3 degradation types, same probability
# and range as Variant 1's Low-Light/Noise (for fair comparison), PLUS Motion
# Blur added (which Variant 1 deliberately excluded due to lack of evidence).
# ---------------------------------------------------------------------------
BLANKET_LOWLIGHT_PROB = 0.35
BLANKET_LOWLIGHT_FACTOR_RANGE = (0.15, 0.85)
BLANKET_NOISE_PROB = 0.35
BLANKET_NOISE_STD_RANGE = (0.02, 0.16)
BLANKET_BLUR_PROB = 0.35
BLANKET_BLUR_KERNEL_RANGE = (5, 17)   # matches Phase 3's motion-blur severity kernels

random.seed(SEED)
np.random.seed(SEED)

OUTPUT_ROOT = "/kaggle/working/phase5_blanket"
TRAINING_DIR = os.path.join(OUTPUT_ROOT, "training")
MODELS_DIR = os.path.join(OUTPUT_ROOT, "models")
RESULTS_DIR = os.path.join(OUTPUT_ROOT, "results")
LOGS_DIR = os.path.join(OUTPUT_ROOT, "logs")
for d in [OUTPUT_ROOT, TRAINING_DIR, MODELS_DIR, RESULTS_DIR, LOGS_DIR]:
    os.makedirs(d, exist_ok=True)

print("Blanket augmentation configuration loaded.")
print("Low-light:", BLANKET_LOWLIGHT_PROB, BLANKET_LOWLIGHT_FACTOR_RANGE)
print("Noise    :", BLANKET_NOISE_PROB, BLANKET_NOISE_STD_RANGE)
print("Blur     :", BLANKET_BLUR_PROB, BLANKET_BLUR_KERNEL_RANGE)

Blanket augmentation configuration loaded.
Low-light: 0.35 (0.15, 0.85)
Noise    : 0.35 (0.02, 0.16)
Blur     : 0.35 (5, 17)

## Cell 4 — Locate Phase 3 output (before-model, clean+degraded test sets)

In [4]:
def find_phase3_root():
    candidates = []
    for root in ("/kaggle/input", "/kaggle/working"):
        for config_path in glob.glob(os.path.join(root, "**", "phase3_config.json"), recursive=True):
            d = os.path.dirname(config_path)
            if os.path.isdir(os.path.join(d, "degraded_datasets")):
                candidates.append(d)
    return sorted(set(candidates))

phase3_candidates = find_phase3_root()
if not phase3_candidates:
    raise FileNotFoundError("No Phase 3 output found. Add the Phase 3 output zip as a Kaggle Input dataset.")
PHASE3_ROOT = phase3_candidates[0]
print("PHASE3_ROOT:", PHASE3_ROOT)

with open(os.path.join(PHASE3_ROOT, "phase3_config.json")) as f:
    phase3_config = json.load(f)

BEFORE_MODEL_PATH = os.path.join(PHASE3_ROOT, "model", "best.pt")
if not os.path.exists(BEFORE_MODEL_PATH):
    cands = glob.glob("/kaggle/input/**/best.pt", recursive=True)
    if not cands:
        raise FileNotFoundError("No baseline best.pt found.")
    BEFORE_MODEL_PATH = cands[0]
print("BEFORE_MODEL_PATH:", BEFORE_MODEL_PATH)

CLEAN_TEST_IMAGES_DIR = os.path.join(PHASE3_ROOT, "clean_test_set", "images")
DEGRADED_DIR = os.path.join(PHASE3_ROOT, "degraded_datasets")
DEGRADATION_DIRS = {
    "Gaussian Noise": os.path.join(DEGRADED_DIR, "gaussian_noise"),
    "Motion Blur": os.path.join(DEGRADED_DIR, "motion_blur"),
    "Low Light": os.path.join(DEGRADED_DIR, "low_light"),
}
for name, d in DEGRADATION_DIRS.items():
    print(f"{name} exists: {os.path.isdir(d)} -> {d}")

SEVERITY_PARAMS = phase3_config.get("severity_params", {})
SEVERITIES = sorted({int(s) for grp in SEVERITY_PARAMS.values() for s in grp.keys()}) or [1, 2, 3, 4]
CLASS_NAMES = phase3_config.get("class_names", ["Fire", "Smoke"])
NUM_CLASSES = len(CLASS_NAMES)
print("Severities:", SEVERITIES, "| Classes:", CLASS_NAMES)

PHASE3_ROOT: /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5
BEFORE_MODEL_PATH: /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/model/best.pt
Gaussian Noise exists: True -> /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise
Motion Blur exists: True -> /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur
Low Light exists: True -> /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light
Severities: [1, 2, 3, 4] | Classes: ['Fire', 'Smoke']

## Cell 5 — Locate / download the training dataset (train+val)

In [5]:
train_data_candidates = glob.glob("/kaggle/input/**/train/images", recursive=True) + \
                         glob.glob("/kaggle/working/**/train/images", recursive=True)

if train_data_candidates:
    TRAIN_DATASET_ROOT = os.path.dirname(os.path.dirname(train_data_candidates[0]))
    print("Using existing dataset at:", TRAIN_DATASET_ROOT)
else:
    print("Downloading from Roboflow...")
    _pip_install("roboflow")
    from roboflow import Roboflow
    ROBOFLOW_API_KEY = "qNZt21Yr4LTdIaH6fUXC"
    rf = Roboflow(api_key=ROBOFLOW_API_KEY)
    project = rf.workspace("md-s-workspace").project("fire_smoke_detection-tmqte")
    dataset = project.version(4).download("yolov11")
    TRAIN_DATASET_ROOT = dataset.location
    print("Downloaded to:", TRAIN_DATASET_ROOT)

DATA_YAML_PATH = os.path.join(TRAIN_DATASET_ROOT, "data.yaml")
print("data.yaml:", DATA_YAML_PATH, "| exists:", os.path.exists(DATA_YAML_PATH))

Using existing dataset at: /kaggle/working/fire_smoke_detection-4
data.yaml: /kaggle/working/fire_smoke_detection-4/data.yaml | exists: True

## Cell 6 — Patch build_transforms with BLANKET (unfiltered) augmentation

Idempotent patch (safe to re-run), identical mechanism to Variant 1's patch --
only the transform class differs (adds Motion Blur, no evidence-gate applied).

In [6]:
from ultralytics.data.dataset import YOLODataset

class BlanketDegradationAugment:
    """Blanket (non-evidence-based) augmentation: applies ALL THREE Phase 3
    degradation types with equal, unfiltered probability -- used only as an
    ablation control against the evidence-constrained targeted (Variant 1) run."""
    def __init__(self, p_lowlight, lowlight_range, p_noise, noise_std_range,
                 p_blur, blur_kernel_range):
        self.p_lowlight = p_lowlight
        self.lowlight_range = lowlight_range
        self.p_noise = p_noise
        self.noise_std_range = noise_std_range
        self.p_blur = p_blur
        self.blur_kernel_range = blur_kernel_range

    def _apply_lowlight(self, img):
        factor = random.uniform(*self.lowlight_range)
        hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV).astype(np.float32)
        hsv[:, :, 2] = np.clip(hsv[:, :, 2] * factor, 0, 255)
        return cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2BGR)

    def _apply_noise(self, img):
        std = random.uniform(*self.noise_std_range)
        img_f = img.astype(np.float32) / 255.0
        noise = np.random.normal(0.0, std, img_f.shape).astype(np.float32)
        return (np.clip(img_f + noise, 0, 1) * 255.0).astype(np.uint8)

    def _apply_blur(self, img):
        k = random.choice(range(self.blur_kernel_range[0], self.blur_kernel_range[1] + 1, 2))
        kernel = np.zeros((k, k), dtype=np.float32)
        kernel[k // 2, :] = 1.0 / k
        return cv2.filter2D(img, -1, kernel)

    def __call__(self, labels):
        img = labels["img"]
        if random.random() < self.p_lowlight:
            img = self._apply_lowlight(img)
        if random.random() < self.p_noise:
            img = self._apply_noise(img)
        if random.random() < self.p_blur:
            img = self._apply_blur(img)
        labels["img"] = img
        return labels


if not hasattr(YOLODataset, "_phase5_true_original_build_transforms"):
    current = YOLODataset.__dict__.get("build_transforms")
    while current is not None and getattr(current, "_is_phase5_patch", False):
        current = current._wrapped_original
    YOLODataset._phase5_true_original_build_transforms = current
    print("Captured the TRUE original build_transforms.")
else:
    print("TRUE original build_transforms already captured -- reusing it.")

_true_original = YOLODataset._phase5_true_original_build_transforms

def _patched_build_transforms(self, hyp=None):
    transforms = _true_original(self, hyp)
    if getattr(self, "augment", False):
        blanket = BlanketDegradationAugment(
            p_lowlight=BLANKET_LOWLIGHT_PROB, lowlight_range=BLANKET_LOWLIGHT_FACTOR_RANGE,
            p_noise=BLANKET_NOISE_PROB, noise_std_range=BLANKET_NOISE_STD_RANGE,
            p_blur=BLANKET_BLUR_PROB, blur_kernel_range=BLANKET_BLUR_KERNEL_RANGE,
        )
        insert_at = len(transforms.transforms) - 1 if len(transforms.transforms) > 0 else 0
        transforms.transforms.insert(insert_at, blanket)
        print(f"[Blanket] Inserted BlanketDegradationAugment at position {insert_at} "
              f"(pipeline now has {len(transforms.transforms)} transforms).")
    return transforms

_patched_build_transforms._is_phase5_patch = True
_patched_build_transforms._wrapped_original = _true_original
YOLODataset.build_transforms = _patched_build_transforms
print("Patched YOLODataset.build_transforms (blanket, idempotent).")

Captured the TRUE original build_transforms.
Patched YOLODataset.build_transforms (blanket, idempotent).

## Cell 7 — Evaluation utility (per-class AP50 included)

In [7]:
def make_data_yaml(images_dir, yaml_path, names):
    split_root = os.path.dirname(images_dir)
    data = {"path": split_root, "train": "images", "val": "images",
            "names": {i: n for i, n in enumerate(names)}}
    with open(yaml_path, "w") as f:
        pyyaml.dump(data, f)
    return yaml_path

def evaluate_model(model, images_dir, name, conf=EVAL_CONF, iou=IOU_THRESHOLD, imgsz=IMG_SIZE):
    yaml_path = os.path.join(LOGS_DIR, f"data_{name}.yaml")
    make_data_yaml(images_dir, yaml_path, CLASS_NAMES)
    metrics = model.val(data=yaml_path, imgsz=imgsz, conf=conf, iou=iou, split="val",
                         device=DEVICE, verbose=False, plots=False, save_json=False)
    per_class_ap50 = {}
    try:
        ap50_per_class = metrics.box.ap50
        for i, cname in enumerate(CLASS_NAMES):
            per_class_ap50[f"{cname}_AP50"] = float(ap50_per_class[i]) if i < len(ap50_per_class) else None
    except Exception:
        for cname in CLASS_NAMES:
            per_class_ap50[f"{cname}_AP50"] = None
    return {
        "Precision": float(metrics.box.mp),
        "Recall": float(metrics.box.mr),
        "mAP50": float(metrics.box.map50),
        "mAP50_95": float(metrics.box.map),
        **per_class_ap50,
    }

def evaluate_all_conditions(model, tag):
    rows = []
    m = evaluate_model(model, CLEAN_TEST_IMAGES_DIR, f"{tag}_clean")
    rows.append({"Model": tag, "Degradation": "Clean", "Severity": 0, **m})
    for deg_name, deg_dir in DEGRADATION_DIRS.items():
        deg_key = deg_name.lower().replace(" ", "_")
        for sev in SEVERITIES:
            sev_dir = os.path.join(deg_dir, f"severity_{sev}", "images")
            if not os.path.isdir(sev_dir):
                continue
            m = evaluate_model(model, sev_dir, f"{tag}_{deg_key}_sev{sev}")
            rows.append({"Model": tag, "Degradation": deg_name, "Severity": sev, **m})
    return pd.DataFrame(rows)

print("Evaluation utility ready.")

Evaluation utility ready.

## Cell 8 — BEFORE evaluation (baseline model, for reference)

In [8]:
before_model = YOLO(BEFORE_MODEL_PATH)
before_df = evaluate_all_conditions(before_model, "Before")
before_csv = os.path.join(RESULTS_DIR, "before_results.csv")
before_df.to_csv(before_csv, index=False)
print("Saved:", before_csv)
before_df

Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
YOLO11s summary (fused): 101 layers, 9,413,574 parameters, 0 gradients, 21.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 85.7±66.4 MB/s, size: 37.1 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/clean_test_set/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.1Kit/s 1.6s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/clean_test_set is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.9it/s 18.4s0.2s
                   all       1715       2790      0.869      0.763      0.828      0.625
Speed: 0.8ms preprocess, 8.1ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 320.3±151.7 MB/s, size: 204.9 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_1/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 834.7it/s 2.1s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_1 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.7it/s 19.0s0.2s
                   all       1715       2790      0.856      0.716      0.784      0.591
Speed: 0.8ms preprocess, 8.4ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.5±1.1 ms, read: 404.0±63.2 MB/s, size: 243.2 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_2/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 845.3it/s 2.0s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_2 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.5it/s 19.6s0.2s
                   all       1715       2790      0.776      0.577      0.636      0.485
Speed: 0.8ms preprocess, 8.7ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.7±1.4 ms, read: 318.0±256.1 MB/s, size: 262.7 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_3/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 831.4it/s 2.1s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_3 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.3it/s 20.3s0.2s
                   all       1715       2790      0.783      0.465      0.516      0.402
Speed: 0.7ms preprocess, 9.1ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 501.8±247.2 MB/s, size: 327.9 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_4/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 846.8it/s 2.0s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_4 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.3s0.2s
                   all       1715       2790      0.664      0.356      0.371      0.276
Speed: 0.7ms preprocess, 9.7ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 126.5±63.8 MB/s, size: 75.3 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_1/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 841.9it/s 2.0s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_1 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.2it/s 21.0s0.2s
                   all       1715       2790      0.877      0.757      0.827      0.624
Speed: 0.7ms preprocess, 9.6ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 148.3±80.6 MB/s, size: 75.9 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_2/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 919.3it/s 1.9s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_2 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.2it/s 20.7s0.2s
                   all       1715       2790      0.872      0.732       0.81      0.603
Speed: 0.7ms preprocess, 9.4ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 114.2±58.6 MB/s, size: 70.3 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_3/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 933.8it/s 1.8s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_3 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.0s0.2s
                   all       1715       2790      0.871       0.69      0.775      0.566
Speed: 0.8ms preprocess, 9.6ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 90.1±33.6 MB/s, size: 45.5 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_4/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 974.4it/s 1.8s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_4 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.2it/s 20.8s0.2s
                   all       1715       2790      0.818      0.657      0.725      0.514
Speed: 0.7ms preprocess, 9.5ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 145.5±63.0 MB/s, size: 75.8 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_1/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 962.2it/s 1.8s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_1 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.2it/s 20.8s0.2s
                   all       1715       2790      0.876      0.759      0.827      0.627
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 91.6±77.0 MB/s, size: 76.8 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_2/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.0Kit/s 1.6s0.0ss
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_2 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.0s0.2s
                   all       1715       2790      0.874      0.762      0.827      0.627
Speed: 0.8ms preprocess, 9.6ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 109.3±59.6 MB/s, size: 56.4 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_3/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.0Kit/s 1.6s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_3 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.2it/s 20.7s0.2s
                   all       1715       2790      0.877      0.751      0.821      0.624
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 50.8±19.2 MB/s, size: 34.3 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_4/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.0Kit/s 1.6s0.0ss
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_4 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.2it/s 20.7s0.2s
                   all       1715       2790      0.878      0.726      0.791      0.599
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.6ms postprocess per image
Saved: /kaggle/working/phase5_blanket/results/before_results.csv

,Model,Degradation,Severity,Precision,Recall,mAP50,mAP50_95,Fire_AP50,Smoke_AP50
0,Before,Clean,0,0.869361,0.762934,0.828040,0.625484,0.872152,0.783928
1,Before,Gaussian Noise,1,0.855555,0.716088,0.783998,0.590691,0.851942,0.716054
2,Before,Gaussian Noise,2,0.775929,0.576955,0.636428,0.484954,0.761404,0.511453
3,Before,Gaussian Noise,3,0.783000,0.465214,0.516404,0.402309,0.644998,0.387811
4,Before,Gaussian Noise,4,0.664069,0.356103,0.370867,0.276117,0.513996,0.227737
5,Before,Motion Blur,1,0.877249,0.756887,0.827109,0.624187,0.873843,0.780376
6,Before,Motion Blur,2,0.871974,0.731861,0.809976,0.603373,0.851552,0.768400
7,Before,Motion Blur,3,0.870828,0.690419,0.775272,0.566320,0.818269,0.732274
8,Before,Motion Blur,4,0.817626,0.657045,0.724563,0.514225,0.757586,0.691539
9,Before,Low Light,1,0.875656,0.758979,0.826797,0.627010,0.870845,0.782749
10,Before,Low Light,2,0.874133,0.762090,0.827069,0.627198,0.870212,0.783926
11,Before,Low Light,3,0.876896,0.751325,0.820986,0.624414,0.867319,0.774653
12,Before,Low Light,4,0.877971,0.725938,0.791391,0.599147,0.843162,0.739619

## Cell 9 — Fresh YOLO11s training with BLANKET augmentation

In [ ]:
blanket_model = YOLO("yolo11s.pt")

train_results = blanket_model.train(
    data=DATA_YAML_PATH,
    epochs=TRAIN_EPOCHS,
    patience=TRAIN_PATIENCE,
    batch=TRAIN_BATCH,
    imgsz=IMG_SIZE,
    device=DEVICE,
    project=TRAINING_DIR,
    name="yolo11s_phase5_blanket",
    exist_ok=True,
    optimizer=TRAIN_OPTIMIZER,
    lr0=TRAIN_LR0,
    lrf=TRAIN_LRF,
    momentum=TRAIN_MOMENTUM,
    weight_decay=TRAIN_WEIGHT_DECAY,
    warmup_epochs=TRAIN_WARMUP_EPOCHS,
    warmup_momentum=TRAIN_WARMUP_MOMENTUM,
    warmup_bias_lr=TRAIN_WARMUP_BIAS_LR,
    seed=TRAIN_SEED,
    deterministic=TRAIN_DETERMINISTIC,
    close_mosaic=TRAIN_CLOSE_MOSAIC,
    cos_lr=TRAIN_COS_LR,
    verbose=True,
    plots=False,
    **BASELINE_AUG,
)

BLANKET_MODEL_PATH = os.path.join(TRAINING_DIR, "yolo11s_phase5_blanket", "weights", "best.pt")
print("\nTraining complete.")
print("BLANKET_MODEL_PATH:", BLANKET_MODEL_PATH, "| exists:", os.path.exists(BLANKET_MODEL_PATH))

bundled_blanket_path = os.path.join(MODELS_DIR, "blanket_best.pt")
shutil.copy2(BLANKET_MODEL_PATH, bundled_blanket_path)
print("Copied best.pt to:", bundled_blanket_path)

## Cell 9b — If disconnected mid-training, run this to resume, then re-run Cell 10 onward

In [9]:
last_pt = os.path.join(TRAINING_DIR, "yolo11s_phase5_blanket", "weights", "last.pt")
if os.path.exists(last_pt):
    resumed_model = YOLO(last_pt)
    resumed_model.train(resume=True)
    BLANKET_MODEL_PATH = os.path.join(TRAINING_DIR, "yolo11s_phase5_blanket", "weights", "best.pt")
    bundled_blanket_path = os.path.join(MODELS_DIR, "blanket_best.pt")
    shutil.copy2(BLANKET_MODEL_PATH, bundled_blanket_path)
    print("Resumed and re-bundled:", bundled_blanket_path)
else:
    print("No last.pt found -- nothing to resume (training likely completed normally via Cell 9).")

Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=12, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=20, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/working/fire_smoke_detection-4/data.yaml, degrees=10.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=150, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.02, hsv_s=0.7, hsv_v=0.5, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/phase5_blanket/training/yolo11s_phase5_blanket/weights/last.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11s_phase5_blanket, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=30, perspective=0.0, plots=False, pose=12.0, pretrained=True, profile=False, project=/kaggle/working/phase5_blanket/training, quantize=None, rect=False, resume=/kaggle/working/phase5_blanket/training/yolo11s_phase5_blanket/weights/last.pt, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/phase5_blanket/training/yolo11s_phase5_blanket, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    820182  ultralytics.nn.modules.head.Detect           [2, 16, None, [128, 256, 512]]
YOLO11s summary: 182 layers, 9,428,566 parameters, 9,428,550 gradients, 21.7 GFLOPs

Transferred 499/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1119.8±328.5 MB/s, size: 44.9 KB)
train: Scanning /kaggle/working/fire_smoke_detection-4/train/labels.cache... 8089 images, 1419 backgrounds, 1 corrupt: 100% ━━━━━━━━━━━━ 8089/8089 3.1Git/s 0.0s
train: /kaggle/working/fire_smoke_detection-4/train/images/middle_-2348-_jpg.rf.a4cd078442e8fac068e55eb1c2557728.jpg: ignoring corrupt image/label: labels mix segment and detection rows
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
[Blanket] Inserted BlanketDegradationAugment at position 7 (pipeline now has 9 transforms).
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 705.8±262.4 MB/s, size: 38.5 KB)
val: Scanning /kaggle/working/fire_smoke_detection-4/valid/labels.cache... 1706 images, 275 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1706/1706 130.1Mit/s 0.0s
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.00046875), 87 bias(decay=0.0)
Resuming training /kaggle/working/phase5_blanket/training/yolo11s_phase5_blanket/weights/last.pt from epoch 72 to 150 total epochs
Using 8088 train, 1706 val images for fraction=1.0 at imgsz=640
Using 2 dataloader workers
Logging results to /kaggle/working/phase5_blanket/training/yolo11s_phase5_blanket
Starting training for 150 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     72/150       3.1G     0.9953     0.8392      1.254         26        640: 100% ━━━━━━━━━━━━ 674/674 4.0it/s 2:500.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 2.7it/s 26.5s0.2ss
                   all       1706       2867       0.86      0.732      0.804      0.573

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

/usr/local/lib/python3.12/dist-packages/ray/train/_internal/session.py:676: UserWarning: `get_trial_id` is meant to only be called inside a function that is executed by a Tuner or Trainer. Returning `None`.
  warnings.warn(

     73/150      3.91G      1.008     0.8525      1.259         25        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:530.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.4it/s 13.5s0.2s
                   all       1706       2867      0.856      0.737      0.803      0.574

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     74/150      3.91G     0.9968     0.8443      1.253         28        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:540.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.861      0.734      0.806      0.575

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     75/150      3.91G     0.9998     0.8401      1.252         31        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:590.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.876      0.721      0.807      0.578

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     76/150      3.91G     0.9815     0.8255      1.244         26        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:570.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.859      0.735      0.807      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     77/150      3.91G      1.002     0.8389      1.252         35        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:530.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.4it/s 13.4s0.2s
                   all       1706       2867      0.859      0.738      0.807      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     78/150      3.91G     0.9872     0.8214      1.243         31        640: 100% ━━━━━━━━━━━━ 674/674 4.0it/s 2:500.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.862      0.733      0.803      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     79/150      3.91G      0.994     0.8167      1.247         39        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:530.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.4it/s 13.3s0.2s
                   all       1706       2867       0.86       0.73      0.804      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     80/150      3.91G     0.9916     0.8256      1.246         41        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:580.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.2it/s 13.9s0.2s
                   all       1706       2867      0.859      0.734      0.803      0.575

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     81/150      3.91G     0.9895     0.8174      1.248         24        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:590.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.861      0.734      0.804      0.577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     82/150      3.91G     0.9895     0.8156      1.242         58        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:570.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.864      0.732      0.805      0.577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     83/150      3.91G     0.9828     0.8148      1.244         41        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.857      0.736      0.806      0.577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     84/150      3.91G      1.004     0.8365      1.257         35        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:550.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.863      0.732      0.806       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     85/150      3.91G      1.027     0.8634      1.273         26        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:570.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.4it/s 13.4s0.2s
                   all       1706       2867      0.866      0.731      0.807       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     86/150      3.91G      1.002     0.8298      1.253         36        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:580.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.852       0.74      0.808      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     87/150      3.91G      1.013     0.8388      1.258         28        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.856      0.742       0.81      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     88/150      3.91G       1.01     0.8355      1.258         39        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:580.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.2it/s 13.7s0.2s
                   all       1706       2867      0.859      0.741       0.81      0.583

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     89/150      3.91G      1.009     0.8346      1.254         31        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:540.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.871      0.732      0.812      0.585

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     90/150      3.91G      0.999     0.8217      1.251         27        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:540.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.2it/s 13.8s0.2s
                   all       1706       2867      0.876      0.731      0.814      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     91/150      3.91G     0.9995     0.8165      1.246         40        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:550.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.871      0.733      0.812      0.585

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     92/150      3.91G     0.9967     0.8128      1.245         27        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.867       0.74      0.814      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     93/150      3.91G     0.9923     0.8177      1.248         36        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:550.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.863      0.744      0.815      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     94/150      3.91G     0.9889     0.8108      1.238         31        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867       0.86      0.745      0.813      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     95/150      3.91G     0.9824     0.8007      1.238         36        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:530.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867       0.86      0.745      0.814      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     96/150      3.91G     0.9919     0.8167      1.244         42        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:530.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.863      0.741      0.814      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     97/150      3.91G     0.9926     0.8071      1.239         47        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.869      0.741      0.812      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     98/150      3.91G     0.9806     0.8023      1.234         35        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.868      0.743      0.814      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     99/150      3.91G     0.9717     0.7906      1.228         26        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:550.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.2it/s 13.7s0.2s
                   all       1706       2867      0.864      0.748      0.813      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    100/150      3.91G     0.9823     0.7952      1.233         53        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:580.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.2it/s 13.7s0.2s
                   all       1706       2867       0.87       0.74      0.814      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    101/150      3.91G     0.9699     0.7846      1.226         36        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:570.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.871       0.74      0.814      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    102/150      3.91G      0.976     0.7778      1.231         50        640: 100% ━━━━━━━━━━━━ 674/674 3.7it/s 2:600.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.874       0.74      0.814      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    103/150      3.91G     0.9672     0.7721      1.228         41        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.871      0.741      0.814      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    104/150      3.91G     0.9592      0.771      1.223         28        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:570.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.2it/s 13.7s0.2s
                   all       1706       2867      0.872      0.742      0.813      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    105/150      3.91G     0.9633     0.7647       1.22         24        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:580.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.875      0.738      0.815      0.588

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    106/150      3.91G     0.9567      0.765      1.218         28        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:540.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.877      0.739      0.815      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    107/150      3.91G     0.9446     0.7536      1.215         43        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:550.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.875      0.742      0.816      0.588

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    108/150      3.91G     0.9592     0.7652      1.219         47        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:550.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.4it/s 13.4s0.2s
                   all       1706       2867      0.868      0.747      0.815      0.588

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    109/150      3.91G     0.9434     0.7457      1.205         34        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:530.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.4it/s 13.4s0.2s
                   all       1706       2867      0.866       0.75      0.817      0.588

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    110/150      3.91G      0.933     0.7397      1.202         49        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:550.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.867      0.747      0.818      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    111/150      3.91G     0.9477     0.7342       1.21         30        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:530.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.868      0.748      0.818      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    112/150      3.91G     0.9455     0.7433      1.206         27        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:570.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.865      0.748      0.817       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    113/150      3.91G     0.9361      0.727        1.2         33        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.862      0.751      0.817       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    114/150      3.91G     0.9327     0.7242        1.2         26        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:550.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.5s0.2s
                   all       1706       2867      0.861      0.751      0.818      0.591

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    115/150      3.91G     0.9269     0.7183      1.196         33        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:540.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.2it/s 13.8s0.2s
                   all       1706       2867      0.863      0.752      0.819      0.592

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    116/150      3.91G     0.9244     0.7249      1.198         28        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.2ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.855      0.758      0.819      0.592

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    117/150      3.91G     0.9338     0.7287      1.204         23        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:580.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.6s0.2s
                   all       1706       2867      0.862      0.753       0.82      0.593

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    118/150      3.91G     0.9211     0.7126      1.197         37        640: 100% ━━━━━━━━━━━━ 674/674 3.9it/s 2:550.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.863      0.755      0.819      0.593

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
    119/150      3.91G     0.9171     0.7121       1.19         38        640: 100% ━━━━━━━━━━━━ 674/674 3.8it/s 2:560.3ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 72/72 5.3it/s 13.7s0.2s
                   all       1706       2867      0.864      0.756       0.82      0.593

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

## Cell 10 — AFTER (Blanket) evaluation on the same Clean + degraded sets

In [10]:
blanket_yolo = YOLO(bundled_blanket_path)
blanket_df = evaluate_all_conditions(blanket_yolo, "Blanket")
blanket_csv = os.path.join(RESULTS_DIR, "blanket_results.csv")
blanket_df.to_csv(blanket_csv, index=False)
print("Saved:", blanket_csv)
blanket_df

Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
YOLO11s summary (fused): 101 layers, 9,413,574 parameters, 0 gradients, 21.4 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 62.7±21.8 MB/s, size: 39.8 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/clean_test_set/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.1Kit/s 1.6s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/clean_test_set is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.3s0.2s
                   all       1715       2790      0.867      0.749      0.823      0.617
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.7±1.0 ms, read: 313.1±52.4 MB/s, size: 177.0 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_1/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.1Kit/s 1.6s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_1 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.0it/s 21.6s0.2s
                   all       1715       2790       0.87      0.749      0.823      0.617
Speed: 0.8ms preprocess, 9.8ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 398.5±143.7 MB/s, size: 234.6 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_2/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.1Kit/s 1.6s<0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_2 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.1s0.2s
                   all       1715       2790      0.866       0.74      0.819      0.615
Speed: 0.8ms preprocess, 9.4ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 524.2±171.1 MB/s, size: 287.8 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_3/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.0Kit/s 1.6s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_3 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.3s0.2s
                   all       1715       2790      0.867      0.732      0.818      0.612
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 514.0±120.4 MB/s, size: 295.8 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_4/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.0Kit/s 1.7s<0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/gaussian_noise/severity_4 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.0it/s 21.5s0.2s
                   all       1715       2790      0.859      0.725      0.806      0.604
Speed: 0.8ms preprocess, 9.7ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 183.0±62.0 MB/s, size: 91.9 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_1/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.0Kit/s 1.7s0.1ss
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_1 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.2s0.2s
                   all       1715       2790      0.874      0.743      0.821      0.617
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 152.3±42.9 MB/s, size: 64.2 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_2/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.1Kit/s 1.6s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_2 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.2s0.2s
                   all       1715       2790      0.861      0.745       0.82      0.616
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 103.8±48.0 MB/s, size: 51.8 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_3/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.1Kit/s 1.6s0.1ss
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_3 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.4s0.2s
                   all       1715       2790      0.874      0.733      0.817      0.612
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 132.7±47.6 MB/s, size: 69.7 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_4/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.1Kit/s 1.6s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/motion_blur/severity_4 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.2s0.2s
                   all       1715       2790      0.867      0.729      0.812      0.606
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 172.8±33.4 MB/s, size: 75.8 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_1/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.1Kit/s 1.6s<0.2s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_1 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.3s0.2s
                   all       1715       2790      0.871      0.745      0.823      0.618
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 92.3±56.7 MB/s, size: 58.1 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_2/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.1Kit/s 1.5s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_2 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.2s0.2s
                   all       1715       2790      0.868      0.749      0.824      0.619
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.6ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 108.8±43.9 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_3/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 1.0Kit/s 1.6s<0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_3 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.2s0.2s
                   all       1715       2790       0.87      0.749      0.823       0.62
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Ultralytics 8.4.133 🚀 Python-3.12.13 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14912MiB)
val: Fast image access ✅ (ping: 0.4±0.9 ms, read: 78.2±21.7 MB/s, size: 34.5 KB)
val: Scanning /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_4/labels... 1715 images, 287 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1715/1715 903.0it/s 1.9s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/datasets/sadiahaiderjaima/dataset-p3-using-p5/degraded_datasets/low_light/severity_4 is not writable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 108/108 5.1it/s 21.2s0.2s
                   all       1715       2790      0.875      0.746      0.818      0.614
Speed: 0.8ms preprocess, 9.5ms inference, 0.0ms loss, 0.7ms postprocess per image
Saved: /kaggle/working/phase5_blanket/results/blanket_results.csv

,Model,Degradation,Severity,Precision,Recall,mAP50,mAP50_95,Fire_AP50,Smoke_AP50
0,Blanket,Clean,0,0.866675,0.748620,0.822813,0.617245,0.867199,0.778428
1,Blanket,Gaussian Noise,1,0.869838,0.748908,0.823093,0.617208,0.869829,0.776358
2,Blanket,Gaussian Noise,2,0.865875,0.740295,0.818875,0.614602,0.865292,0.772459
3,Blanket,Gaussian Noise,3,0.866930,0.732350,0.817555,0.611899,0.867079,0.768031
4,Blanket,Gaussian Noise,4,0.859428,0.725346,0.805946,0.603566,0.860532,0.751359
5,Blanket,Motion Blur,1,0.873934,0.742515,0.821299,0.617391,0.866511,0.776086
6,Blanket,Motion Blur,2,0.861156,0.745431,0.819856,0.616258,0.866465,0.773247
7,Blanket,Motion Blur,3,0.874199,0.733311,0.816586,0.612275,0.863199,0.769972
8,Blanket,Motion Blur,4,0.866732,0.728510,0.811967,0.606107,0.857561,0.766373
9,Blanket,Low Light,1,0.870612,0.745377,0.822780,0.618290,0.868696,0.776865
10,Blanket,Low Light,2,0.867869,0.748629,0.823535,0.619320,0.869009,0.778061
11,Blanket,Low Light,3,0.870315,0.749296,0.822893,0.619573,0.865871,0.779916
12,Blanket,Low Light,4,0.875099,0.745656,0.818001,0.613583,0.864639,0.771363

## Cell 11 — Comparison table: Before vs Blanket (values only, matches Table 2's format)

In [11]:
merged = before_df.merge(blanket_df, on=["Degradation", "Severity"], suffixes=("_Before", "_Blanket"))

for metric in ["Precision", "Recall", "mAP50", "mAP50_95"]:
    merged[f"{metric}_Improvement_Pct"] = (
        (merged[f"{metric}_Blanket"] - merged[f"{metric}_Before"]) / merged[f"{metric}_Before"].replace(0, np.nan)
    ) * 100.0

comparison_csv = os.path.join(RESULTS_DIR, "before_vs_blanket_comparison.csv")
merged.to_csv(comparison_csv, index=False)
print("Saved:", comparison_csv)

cols = ["Degradation", "Severity",
        "Precision_Before", "Precision_Blanket",
        "Recall_Before", "Recall_Blanket",
        "mAP50_Before", "mAP50_Blanket",
        "mAP50_95_Before", "mAP50_95_Blanket",
        "mAP50_Improvement_Pct"]
print(merged[cols].to_string(index=False))

Saved: /kaggle/working/phase5_blanket/results/before_vs_blanket_comparison.csv
   Degradation  Severity  Precision_Before  Precision_Blanket  Recall_Before  Recall_Blanket  mAP50_Before  mAP50_Blanket  mAP50_95_Before  mAP50_95_Blanket  mAP50_Improvement_Pct
         Clean         0          0.869361           0.866675       0.762934        0.748620      0.828040       0.822813         0.625484          0.617245              -0.631172
Gaussian Noise         1          0.855555           0.869838       0.716088        0.748908      0.783998       0.823093         0.590691          0.617208               4.986637
Gaussian Noise         2          0.775929           0.865875       0.576955        0.740295      0.636428       0.818875         0.484954          0.614602              28.667265
Gaussian Noise         3          0.783000           0.866930       0.465214        0.732350      0.516404       0.817555         0.402309          0.611899              58.316753
Gaussian Noise         4          0.664069           0.859428       0.356103        0.725346      0.370867       0.805946         0.276117          0.603566             117.314176
   Motion Blur         1          0.877249           0.873934       0.756887        0.742515      0.827109       0.821299         0.624187          0.617391              -0.702485
   Motion Blur         2          0.871974           0.861156       0.731861        0.745431      0.809976       0.819856         0.603373          0.616258               1.219806
   Motion Blur         3          0.870828           0.874199       0.690419        0.733311      0.775272       0.816586         0.566320          0.612275               5.328955
   Motion Blur         4          0.817626           0.866732       0.657045        0.728510      0.724563       0.811967         0.514225          0.606107              12.063034
     Low Light         1          0.875656           0.870612       0.758979        0.745377      0.826797       0.822780         0.627010          0.618290              -0.485796
     Low Light         2          0.874133           0.867869       0.762090        0.748629      0.827069       0.823535         0.627198          0.619320              -0.427280
     Low Light         3          0.876896           0.870315       0.751325        0.749296      0.820986       0.822893         0.624414          0.619573               0.232339
     Low Light         4          0.877971           0.875099       0.725938        0.745656      0.791391       0.818001         0.599147          0.613583               3.362476

## Cell 12 — Save config + ZIP

In [12]:
config = {
    "run_type": "Blanket augmentation (ablation control, no evidence gate)",
    "before_model_path": BEFORE_MODEL_PATH,
    "blanket_model_path": bundled_blanket_path,
    "training_hyperparameters": {
        "epochs": TRAIN_EPOCHS, "batch": TRAIN_BATCH, "optimizer": TRAIN_OPTIMIZER,
        "lr0": TRAIN_LR0, "seed": TRAIN_SEED,
    },
    "blanket_augmentation": {
        "lowlight_prob": BLANKET_LOWLIGHT_PROB, "lowlight_range": BLANKET_LOWLIGHT_FACTOR_RANGE,
        "noise_prob": BLANKET_NOISE_PROB, "noise_range": BLANKET_NOISE_STD_RANGE,
        "blur_prob": BLANKET_BLUR_PROB, "blur_kernel_range": BLANKET_BLUR_KERNEL_RANGE,
    },
    "class_names": CLASS_NAMES,
}
config_path = os.path.join(OUTPUT_ROOT, "phase5_blanket_config.json")
with open(config_path, "w") as f:
    json.dump(config, f, indent=2)
print("Saved:", config_path)

zip_path = shutil.make_archive("/kaggle/working/phase5_blanket_results", "zip", OUTPUT_ROOT)
print("\nFINAL ZIP:")
print(" ", zip_path)

Saved: /kaggle/working/phase5_blanket/phase5_blanket_config.json

FINAL ZIP:
  /kaggle/working/phase5_blanket_results.zip